FROM docker.elastic.co/logstash/logstash:8.6.2
COPY logstash.conf /usr/share/logstash/config
CMD [ "./bin/logstash", "-f" , "config/logstash.conf"]
EXPOSE 9200


#ENV LOG_FILE_PATH=/tmp/sample

#FROM openjdk:17

#ADD sample-0.0.1-SNAPSHOT.jar sample-0.0.1-SNAPSHOT.jar

#ENTRYPOINT [ "java", "-jar" , "sample-0.0.1-SNAPSHOT.jar" ]
